import { Category, Product, DealOffer, DealerTier, FAQItem, Currency } from './types.js';

export const CURRENCIES: Currency[] = [
  { code: 'USD', symbol: '$', rate: 1, name: 'USD (US Dollar)' },
  { code: 'NPR', symbol: 'रू ', rate: 134, name: 'NPR (Nepalese Rupee)' },
  { code: 'INR', symbol: '₹', rate: 84, name: 'INR (Indian Rupee)' },
  { code: 'EUR', symbol: '€', rate: 0.92, name: 'EUR (Euro)' },
  { code: 'GBP', symbol: '£', rate: 0.78, name: 'GBP (British Pound)' },
];

export const CATEGORIES: Category[] = [
  {
    id: 'grocery',
    name: 'Grocery & Gourmet',
    shortName: 'Grocery',
    slug: 'grocery',
    tagline: 'Farm fresh produce, authentic pantry staples & organics',
    description: 'Explore organic grains, cold-pressed oils, mountain teas, exotic spices, artisan snacks, and daily fresh groceries delivered in hours.',
    iconName: 'ShoppingBag',
    bannerImage: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1200&q=80',
    subcategories: ['Organic Staples', 'Spices & Seasonings', 'Tea & Coffee', 'Dry Fruits & Nuts', 'Oils & Ghee', 'Snacks & Beverages'],
    popularBrands: ['Himalayan Harvest', 'Organic Tattva', 'Valley Pure', 'Mountain Brew', 'Nature Basket'],
    itemCount: 1420,
    colorScheme: {
      bg: 'bg-emerald-50',
      text: 'text-emerald-800',
      badge: 'bg-emerald-600 text-white',
      border: 'border-emerald-200'
    }
  },
  {
    id: 'electronics',
    name: 'Electronics & Gadgets',
    shortName: 'Electronics',
    slug: 'electronics',
    tagline: 'Next-gen computing, immersive audio & smart gear',
    description: 'High-performance laptops, studio noise-canceling headphones, 4K cameras, mechanical peripherals, and smart displays with full manufacturer warranty.',
    iconName: 'Laptop',
    bannerImage: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=1200&q=80',
    subcategories: ['Laptops & Desktops', 'Audio & Sound', 'Cameras & Video', 'Smart Home & IoT', 'Wearables', 'Gaming Gear'],
    popularBrands: ['ApexTech', 'AcousticPro', 'LumixVision', 'NovaCore', 'PulseAudio'],
    itemCount: 980,
    colorScheme: {
      bg: 'bg-indigo-50',
      text: 'text-indigo-800',
      badge: 'bg-indigo-600 text-white',
      border: 'border-indigo-200'
    }
  },
  {
    id: 'fashion',
    name: 'Fashion & Apparel',
    shortName: 'Fashion',
    slug: 'fashion',
    tagline: 'Contemporary aesthetics, handcrafted footwear & essentials',
    description: 'Curated premium clothing, cashmere overcoats, organic linen shirts, genuine leather shoes, artisan shawls, and tailored accessories for every season.',
    iconName: 'Shirt',
    bannerImage: 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=1200&q=80',
    subcategories: ["Men's Wear", "Women's Collection", 'Handcrafted Footwear', 'Ethnic & Cashmere', 'Eyewear & Watches', 'Bags & Wallets'],
    popularBrands: ['Velvet Thread', 'Artisan Guild', 'AeroWeave', 'SilkRoad Couture', 'Nordic Craft'],
    itemCount: 2350,
    colorScheme: {
      bg: 'bg-amber-50',
      text: 'text-amber-900',
      badge: 'bg-amber-600 text-white',
      border: 'border-amber-200'
    }
  },
  {
    id: 'beauty',
    name: 'Beauty & Personal Care',
    shortName: 'Beauty',
    slug: 'beauty',
    tagline: 'Clean skincare, luxury fragrances & botanical serums',
    description: 'Dermatologist-tested skincare, French boutique perfumes, cold-pressed face oils, botanical haircare, and clean cosmetic formulations.',
    iconName: 'Sparkles',
    bannerImage: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1200&q=80',
    subcategories: ['Skincare Serums', 'Luxury Perfumes', 'Hair Treatment', 'Organic Face Oils', 'Bath & Body', 'Clean Makeup'],
    popularBrands: ['Botanica Lab', 'L\'Aura Paris', 'Elysian Glow', 'PureDerma', 'Luminis'],
    itemCount: 840,
    colorScheme: {
      bg: 'bg-rose-50',
      text: 'text-rose-900',
      badge: 'bg-rose-600 text-white',
      border: 'border-rose-200'
    }
  },
  {
    id: 'health-wellness',
    name: 'Health & Wellness',
    shortName: 'Health',
    slug: 'health-wellness',
    tagline: 'Herbal vitality, clean nutrition & fitness essentials',
    description: 'Authentic Himalayan Shilajit, pure grass-fed whey proteins, organic Ayurvedic adaptogens, deep tissue recovery massagers, and eco yoga mats.',
    iconName: 'HeartPulse',
    bannerImage: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=1200&q=80',
    subcategories: ['Ayurveda & Herbal', 'Sports Nutrition', 'Recovery & Massage', 'Vitamins & Minerals', 'Yoga & Fitness', 'Daily Immunity'],
    popularBrands: ['VedaVital', 'OptiPure Nutra', 'PranaPeak', 'ApexRecovery', 'BioBalance'],
    itemCount: 650,
    colorScheme: {
      bg: 'bg-teal-50',
      text: 'text-teal-900',
      badge: 'bg-teal-600 text-white',
      border: 'border-teal-200'
    }
  },
  {
    id: 'home-kitchen',
    name: 'Home & Kitchen',
    shortName: 'Home & Kitchen',
    slug: 'home-kitchen',
    tagline: 'Culinary cookware, smart cleaning & artisanal decor',
    description: 'Heavyweight enameled Dutch ovens, barista espresso makers, intelligent robot vacuums, damascus chef knives, and ambient lighting.',
    iconName: 'Home',
    bannerImage: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1200&q=80',
    subcategories: ['Cookware & Bakeware', 'Coffee & Espresso', 'Smart Appliances', 'Cutlery & Prep', 'Home Decor & Lighting', 'Storage & Organization'],
    popularBrands: ['CastIron Artisan', 'BaristaCraft', 'RoboClean Pro', 'Damascus Forge', 'Nordic Living'],
    itemCount: 1120,
    colorScheme: {
      bg: 'bg-orange-50',
      text: 'text-orange-900',
      badge: 'bg-orange-600 text-white',
      border: 'border-orange-200'
    }
  },
  {
    id: 'mobile-accessories',
    name: 'Mobile & Accessories',
    shortName: 'Mobile & Acc',
    slug: 'mobile-accessories',
    tagline: 'Flagship 5G devices, GaN chargers & magnetic gear',
    description: 'High-speed wireless chargers, kevlar & carbon magnetic cases, multi-device power banks, ultra-low latency TWS earbuds, and camera lens protectors.',
    iconName: 'Smartphone',
    bannerImage: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80',
    subcategories: ['Flagship Smartphones', 'GaN Fast Chargers', 'Magnetic Cases & Covers', 'Power Banks', 'True Wireless Earbuds', 'Cables & Docks'],
    popularBrands: ['HyperCharge', 'ArmorShield', 'VoltStream', 'SonicBuds', 'MagSnap'],
    itemCount: 1560,
    colorScheme: {
      bg: 'bg-blue-50',
      text: 'text-blue-900',
      badge: 'bg-blue-600 text-white',
      border: 'border-blue-200'
    }
  }
];

export const PRODUCTS: Product[] = [
  // Grocery
  {
    id: 'gro-1',
    name: 'Himalayan Organic Basmati Rice (Aged 2 Years)',
    slug: 'himalayan-organic-basmati-rice-aged',
    category: 'grocery',
    categoryName: 'Grocery & Gourmet',
    subcategory: 'Organic Staples',
    brand: 'Himalayan Harvest',
    price: 24.50,
    originalPrice: 32.00,
    discountPercent: 23,
    cashbackPercent: 10,
    rating: 4.9,
    reviewCount: 428,
    inStock: true,
    stockCount: 85,
    isBestSeller: true,
    isFeatured: true,
    badge: 'Farm Direct',
    images: [
      'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Hand-harvested from the foothills of the Himalayas and naturally aged in wooden silos for 24 months to yield extra-long slender grains with an exquisite aromatic bouquet.',
    shortDesc: 'Aged 24 months, aromatic long-grain organic basmati rice (5kg pack).',
    features: ['100% Certified Organic & Non-GMO', 'Naturally aged for 2 full years', 'Fluffy, non-sticky extra long grain', 'Gluten-Free & Pesticide Free'],
    specs: { 'Net Weight': '5 kg', 'Packaging': 'Aroma-Lock Eco Pouch', 'Origin': 'Mustang Valley Foothills', 'Shelf Life': '24 Months' },
    tags: ['organic', 'basmati', 'rice', 'staple', 'himalayan', 'pantry'],
    sku: 'GRO-BAS-001',
    variants: [{ name: 'Pack Size', options: ['2 kg', '5 kg', '10 kg Bulk Bag'] }],
    deliveryEstimate: 'Express 2-4 Hours in Metro areas',
    returnDays: 7,
    warranty: '100% Freshness Guarantee'
  },
  {
    id: 'gro-2',
    name: 'Cold-Pressed Extra Virgin Mustard Oil & Raw Honey Duo',
    slug: 'cold-pressed-mustard-oil-raw-honey-duo',
    category: 'grocery',
    categoryName: 'Grocery & Gourmet',
    subcategory: 'Oils & Ghee',
    brand: 'Valley Pure',
    price: 28.00,
    originalPrice: 38.00,
    discountPercent: 26,
    cashbackPercent: 12,
    rating: 4.8,
    reviewCount: 194,
    inStock: true,
    stockCount: 42,
    isFlashSale: true,
    flashSaleEndsInSeconds: 14200,
    flashClaimedPercent: 78,
    badge: 'Flash Deal',
    images: [
      'https://images.unsplash.com/photo-1471943311424-646960669fbc?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Traditional wood-pressed virgin mustard oil with pungent authentic bite, paired with raw unfiltered wild forest honeycomb honey harvested at 2,200m altitude.',
    shortDesc: 'Wood-pressed mustard oil (1L) + Raw wild forest honey (500g).',
    features: ['Extracted via low-temperature wooden churner (Kachi Ghani)', 'Rich in natural Omega-3 fatty acids', 'Unpasteurized honey with live enzymes', 'Zero chemical processing or blends'],
    specs: { 'Oil Volume': '1 Liter Glass Bottle', 'Honey Weight': '500g Glass Jar', 'Processing': 'Zero Heat Cold Press', 'Harvest Date': 'Fresh Batch 2026' },
    tags: ['mustard oil', 'raw honey', 'cold pressed', 'organic', 'gourmet'],
    sku: 'GRO-DUO-002',
    deliveryEstimate: 'Same day delivery available',
    returnDays: 7,
    warranty: 'Purity Tested Certified'
  },
  {
    id: 'gro-3',
    name: 'Artisanal Single-Estate Darjeeling First Flush Tea',
    slug: 'single-estate-darjeeling-first-flush-tea',
    category: 'grocery',
    categoryName: 'Grocery & Gourmet',
    subcategory: 'Tea & Coffee',
    brand: 'Mountain Brew',
    price: 36.00,
    originalPrice: 48.00,
    discountPercent: 25,
    cashbackPercent: 15,
    rating: 4.95,
    reviewCount: 312,
    inStock: true,
    stockCount: 60,
    isNewArrival: true,
    isFeatured: true,
    badge: 'Reserve Grade',
    images: [
      'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Known as the Champagne of Teas, this spring harvest whole-leaf tea delivers delicate muscatel floral notes, luminous amber liquor, and a crisp, lingering finish.',
    shortDesc: 'Spring harvest hand-plucked whole leaf reserve tea in airtight tin (250g).',
    features: ['100% Hand-plucked two leaves and a bud', 'High elevation 6,000 ft organic garden', 'Muscatel notes with subtle stone fruit sweetness', 'Sealed in double-lid collector tin'],
    specs: { 'Weight': '250 grams', 'Elevation': '1,850m', 'Harvest': 'Spring 2026', 'Caffeine': 'Medium-High' },
    tags: ['tea', 'darjeeling', 'organic tea', 'first flush', 'gourmet'],
    sku: 'GRO-TEA-003',
    deliveryEstimate: 'Delivered in 24 hours',
    returnDays: 15,
    warranty: 'Estate Origin Certificate'
  },

  // Electronics
  {
    id: 'ele-1',
    name: 'ApexTech Studio Pro ANC Wireless Headphones',
    slug: 'apextech-studio-pro-anc-wireless-headphones',
    category: 'electronics',
    categoryName: 'Electronics & Gadgets',
    subcategory: 'Audio & Sound',
    brand: 'ApexTech',
    price: 189.00,
    originalPrice: 249.00,
    discountPercent: 24,
    cashbackPercent: 15,
    rating: 4.85,
    reviewCount: 680,
    inStock: true,
    stockCount: 38,
    isFlashSale: true,
    flashSaleEndsInSeconds: 8400,
    flashClaimedPercent: 91,
    isBestSeller: true,
    badge: 'Top Audio 2026',
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Engineered with custom 45mm beryllium drivers, hybrid active noise cancellation with 40dB reduction, spatial audio head-tracking, and ultra-plush memory foam earcups.',
    shortDesc: 'Hybrid 40dB ANC, 55-hour battery life, Hi-Res LDAC spatial audio.',
    features: ['55 Hours continuous playback on single charge', 'Hybrid ANC with 3 transparency modes', 'Bluetooth 5.4 + Multipoint Dual Device Pairing', 'Aircraft-grade aluminum headband with magnetic ear cushions'],
    specs: { 'Driver Size': '45mm Custom Beryllium', 'Battery': '55 Hours (ANC On: 42h)', 'Weight': '265g', 'Fast Charge': '10 min for 5 hours' },
    tags: ['headphones', 'anc', 'wireless', 'audio', 'hi-res', 'apextech'],
    sku: 'ELE-AUD-001',
    variants: [{ name: 'Color', options: ['Space Obsidian', 'Arctic Silver', 'Champagne Gold'] }],
    deliveryEstimate: 'Next Day Express Shipping',
    returnDays: 30,
    warranty: '2 Years Comprehensive Replacement Warranty'
  },
  {
    id: 'ele-2',
    name: 'NovaCore UltraBook 16" OLED (M3 32GB 1TB SSD)',
    slug: 'novacore-ultrabook-16-oled-laptop',
    category: 'electronics',
    categoryName: 'Electronics & Gadgets',
    subcategory: 'Laptops & Desktops',
    brand: 'NovaCore',
    price: 1399.00,
    originalPrice: 1699.00,
    discountPercent: 18,
    cashbackPercent: 8,
    rating: 4.9,
    reviewCount: 215,
    inStock: true,
    stockCount: 14,
    isFeatured: true,
    badge: 'Creator Choice',
    images: [
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Stunning 16-inch 3.2K 120Hz OLED screen with 100% DCI-P3 color accuracy, ultra-efficient 12-core processor, vapor chamber cooling, and CNC aluminum unibody weighing just 1.58kg.',
    shortDesc: '3.2K 120Hz OLED, 12-core AI chip, 32GB LPDDR5X, 1TB NVMe Gen4.',
    features: ['16" 3.2K OLED 120Hz 600-nits Display', 'Magnesium-aluminum 14.8mm slim chassis', 'All-day 18-hour battery with 100W GaN charger', 'Quad studio microphones & 1080p IR webcam'],
    specs: { 'Display': '16.0" 3.2K 120Hz OLED', 'RAM': '32GB LPDDR5X', 'Storage': '1TB NVMe PCIe 4.0', 'Weight': '1.58 kg' },
    tags: ['laptop', 'oled', 'ultrabook', 'creator', 'gaming', 'novacore'],
    sku: 'ELE-LAP-002',
    variants: [{ name: 'Configuration', options: ['32GB RAM / 1TB SSD', '64GB RAM / 2TB SSD'] }],
    deliveryEstimate: 'Insured White-Glove Courier',
    returnDays: 15,
    warranty: '2 Years Onsite Global Warranty'
  },
  {
    id: 'ele-3',
    name: 'LumixVision 4K Cinema Pocket Creator Camera',
    slug: 'lumixvision-4k-cinema-pocket-creator-camera',
    category: 'electronics',
    categoryName: 'Electronics & Gadgets',
    subcategory: 'Cameras & Video',
    brand: 'LumixVision',
    price: 749.00,
    originalPrice: 899.00,
    discountPercent: 17,
    cashbackPercent: 10,
    rating: 4.8,
    reviewCount: 142,
    inStock: true,
    stockCount: 22,
    isNewArrival: true,
    badge: '4K 120FPS',
    images: [
      'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Compact cinema powerhouse equipped with a 1-inch BSI sensor, 10-bit 4:2:2 D-Log video recording, 3-axis motorized mechanical gimbal stabilization, and wireless audio receiver.',
    shortDesc: '1" BSI Sensor, 4K 120FPS 10-bit, 3-axis built-in mechanical stabilization.',
    features: ['Pocket-sized with motorized 3-axis stabilization', '10-bit D-Log recording with 13 stops dynamic range', 'AI subject tracking and facial auto-framing', 'Dual magnetic mount with wireless lapel mic'],
    specs: { 'Sensor': '1.0-inch BSI CMOS 20MP', 'Video Resolution': '4K at 120fps / 1080p at 240fps', 'Storage': 'UHS-II MicroSD up to 1TB', 'Battery': '160 min 4K recording' },
    tags: ['camera', '4k', 'vlogging', 'cinema', 'gimbal', 'creator'],
    sku: 'ELE-CAM-003',
    deliveryEstimate: 'Ships within 12 hours',
    returnDays: 15,
    warranty: '1 Year Full Replacement'
  },

  // Fashion
  {
    id: 'fas-1',
    name: 'Artisan Handcrafted Goodyear Welted Chelsea Boots',
    slug: 'artisan-handcrafted-chelsea-boots',
    category: 'fashion',
    categoryName: 'Fashion & Apparel',
    subcategory: 'Handcrafted Footwear',
    brand: 'Artisan Guild',
    price: 165.00,
    originalPrice: 220.00,
    discountPercent: 25,
    cashbackPercent: 12,
    rating: 4.92,
    reviewCount: 388,
    inStock: true,
    stockCount: 29,
    isBestSeller: true,
    isFeatured: true,
    badge: 'Italian Full-Grain',
    images: [
      'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Built by third-generation master bootmakers using supple Italian full-grain pull-up leather, Goodyear welt construction for infinite resoling, and a cushioned cork footbed that molds to your feet.',
    shortDesc: 'Italian full-grain leather, Goodyear welted, Vibram rubber half-sole.',
    features: ['Full-grain pull-up leather develops rich vintage patina', 'Resoleable Goodyear welt 360 construction', 'Dual-density memory foam & natural cork midsole', 'Heavy-duty elastic gusset with pull tabs'],
    specs: { 'Upper': '1.8mm Full Grain Pull-up Leather', 'Sole': 'Vibram Commando Lug / Leather Stack', 'Lining': 'Full Calfskin Leather', 'Construction': 'Goodyear Welted' },
    tags: ['boots', 'chelsea boots', 'leather', 'shoes', 'handmade', 'artisan'],
    sku: 'FAS-BOO-001',
    variants: [{ name: 'Size (US)', options: ['8', '9', '10', '11', '12'] }, { name: 'Color', options: ['Vintage Walnut Brown', 'Midnight Black', 'Rich Oxblood'] }],
    deliveryEstimate: 'Free 2-day delivery',
    returnDays: 30,
    warranty: 'Lifetime Craftsmanship Guarantee'
  },
  {
    id: 'fas-2',
    name: 'Pure Himalayan Cashmere Hand-Woven Shawl',
    slug: 'pure-himalayan-cashmere-hand-woven-shawl',
    category: 'fashion',
    categoryName: 'Fashion & Apparel',
    subcategory: 'Ethnic & Cashmere',
    brand: 'SilkRoad Couture',
    price: 145.00,
    originalPrice: 195.00,
    discountPercent: 26,
    cashbackPercent: 15,
    rating: 4.96,
    reviewCount: 270,
    inStock: true,
    stockCount: 18,
    isNewArrival: true,
    badge: '100% Grade A Cashmere',
    images: [
      'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Spun from the underbelly fleece of high-altitude mountain capra hircus goats at 4,000m, this cloud-soft shawl features delicate eyelash fringe and thermal warmth at featherweight 120g.',
    shortDesc: '100% Grade-A Mountain Cashmere with artisan eyelash fringe (200x70cm).',
    features: ['Superfine 14.5 micron fiber softness', 'Weaved on traditional wooden handlooms', 'Zero synthetic blends or chemical softeners', 'Includes silk gift sleeve and cedar storage pouch'],
    specs: { 'Material': '100% Pure Himalayan Cashmere', 'Dimensions': '200 cm x 70 cm', 'Weight': '125 grams', 'Weave': 'Diamond Weave (Chashm-e-Bulbul)' },
    tags: ['cashmere', 'shawl', 'pashmina', 'fashion', 'luxury', 'warm'],
    sku: 'FAS-SHA-002',
    variants: [{ name: 'Color', options: ['Natural Oatmeal', 'Dusty Rose', 'Deep Sapphire', 'Charcoal Heather'] }],
    deliveryEstimate: 'Next Day Dispatch',
    returnDays: 30,
    warranty: 'Authenticity & Purity Certificate'
  },
  {
    id: 'fas-3',
    name: 'Tailored French Linen Relaxed Cut Shirt',
    slug: 'tailored-french-linen-relaxed-shirt',
    category: 'fashion',
    categoryName: 'Fashion & Apparel',
    subcategory: "Men's Wear",
    brand: 'Nordic Craft',
    price: 58.00,
    originalPrice: 78.00,
    discountPercent: 26,
    cashbackPercent: 10,
    rating: 4.78,
    reviewCount: 210,
    inStock: true,
    stockCount: 65,
    isFlashSale: true,
    flashSaleEndsInSeconds: 16800,
    flashClaimedPercent: 62,
    badge: 'Summer Essential',
    images: [
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Pre-washed Normandy flax linen that breathes effortlessly in hot climates, styled with a spread collar, mother-of-pearl buttons, and tailored clean sleeve plackets.',
    shortDesc: '100% Normandy flax linen, garment dyed & pre-shrunk.',
    features: ['100% Long-staple French Flax Linen', 'Garment washed for immediate buttery softness', 'Natural mother-of-pearl cross-stitched buttons', 'Relaxed modern fit for effortless styling'],
    specs: { 'Fabric': '100% European Flax (160 GSM)', 'Fit': 'Relaxed Tailored', 'Care': 'Machine Wash Cold / Air Dry' },
    tags: ['linen shirt', 'summer fashion', 'menswear', 'casual', 'organic'],
    sku: 'FAS-SHI-003',
    variants: [{ name: 'Size', options: ['S', 'M', 'L', 'XL', 'XXL'] }, { name: 'Color', options: ['Crisp White', 'Sage Olive', 'Sky Blue', 'Sand Beige'] }],
    deliveryEstimate: 'Standard 24-48h Delivery',
    returnDays: 15,
    warranty: 'Stitch & Fabric Guarantee'
  },

  // Beauty
  {
    id: 'bea-1',
    name: 'Elysian Glow Multi-Molecular Hyaluronic Acid Serum',
    slug: 'elysian-glow-hyaluronic-acid-serum',
    category: 'beauty',
    categoryName: 'Beauty & Personal Care',
    subcategory: 'Skincare Serums',
    brand: 'Elysian Glow',
    price: 34.00,
    originalPrice: 48.00,
    discountPercent: 29,
    cashbackPercent: 15,
    rating: 4.9,
    reviewCount: 520,
    inStock: true,
    stockCount: 95,
    isBestSeller: true,
    isFeatured: true,
    badge: 'Dermatologist Loved',
    images: [
      'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1608248597358-00a442d8f9a2?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Infused with 7 distinct molecular weights of hyaluronic acid, vegan ceramides, and fermented centella asiatica to penetrate into deep dermal layers for bouncy, glass-skin hydration.',
    shortDesc: '7-weight Hyaluronic Acid + Vegan Ceramides + 5% Niacinamide (50ml).',
    features: ['Clinically proven +185% instant skin barrier hydration', 'Fragrance-free, oil-free, non-comedogenic', 'Fast absorbing glass-dropper dispenser', 'Cruelty-free & 100% Clean formulation'],
    specs: { 'Volume': '50 ml / 1.7 fl oz', 'Skin Type': 'All Skin Types & Sensitive Skin', 'Formulation': 'Lightweight Water Gel', 'pH Level': '5.5 Balanced' },
    tags: ['hyaluronic acid', 'serum', 'skincare', 'hydration', 'clean beauty'],
    sku: 'BEA-SER-001',
    deliveryEstimate: 'Same-day delivery in select cities',
    returnDays: 30,
    warranty: 'Dermatology Safety Certified'
  },
  {
    id: 'bea-2',
    name: 'L\'Aura Paris Extrait de Parfum (Santal & Bergamot)',
    slug: 'laura-paris-extrait-de-parfum-santal-bergamot',
    category: 'beauty',
    categoryName: 'Beauty & Personal Care',
    subcategory: 'Luxury Perfumes',
    brand: 'L\'Aura Paris',
    price: 88.00,
    originalPrice: 120.00,
    discountPercent: 27,
    cashbackPercent: 20,
    rating: 4.88,
    reviewCount: 310,
    inStock: true,
    stockCount: 30,
    isFlashSale: true,
    flashSaleEndsInSeconds: 11200,
    flashClaimedPercent: 84,
    badge: '30% Oil Concentration',
    images: [
      'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'An intoxicating woody aromatic blend opening with sparkling Calabrian bergamot and pink pepper, leading to a creamy heart of Mysore sandalwood, amber resin, and velvety cardamom.',
    shortDesc: 'Extrait de Parfum (100ml) with 14+ hours longevity and magnetic cap.',
    features: ['30% High oil concentration for 14+ hour projection', 'Natural Mysore Sandalwood & Bergamot oils', 'Heavyweight fluted crystal flacon with magnetic cap', 'Unisex signature scent profile'],
    specs: { 'Size': '100 ml / 3.4 oz', 'Concentration': 'Extrait de Parfum', 'Top Notes': 'Calabrian Bergamot, Cardamom', 'Base Notes': 'Mysore Sandalwood, Amber, Cedarwood' },
    tags: ['perfume', 'fragrance', 'sandalwood', 'luxury', 'beauty'],
    sku: 'BEA-PER-002',
    deliveryEstimate: 'Insured Fragrance Shipping',
    returnDays: 15,
    warranty: '100% Original Brand Authentic'
  },

  // Health & Wellness
  {
    id: 'hea-1',
    name: 'PranaPeak Grade A+ Himalayan Pure Shilajit Resin (Gold Grade)',
    slug: 'pranapeak-himalayan-shilajit-resin-gold-grade',
    category: 'health-wellness',
    categoryName: 'Health & Wellness',
    subcategory: 'Ayurveda & Herbal',
    brand: 'PranaPeak',
    price: 42.00,
    originalPrice: 60.00,
    discountPercent: 30,
    cashbackPercent: 15,
    rating: 4.95,
    reviewCount: 840,
    inStock: true,
    stockCount: 110,
    isBestSeller: true,
    isFeatured: true,
    badge: '>85% Fulvic Acid',
    images: [
      'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Hand-sourced at 18,000+ feet in the Great Himalayas, purified using traditional triphala water filtration, lab-tested with >85% fulvic acid and 84+ ionic trace minerals for cellular energy and stamina.',
    shortDesc: 'Pure Gold Grade Himalayan Shilajit resin with stainless dosing spoon (50g).',
    features: ['Wild harvested at 18,000 ft altitude', 'Contains over 84+ essential trace minerals', 'Third-party heavy-metal & microbial lab tested', 'Boosts cellular ATP energy, focus, and vitality'],
    specs: { 'Net Weight': '50 grams Resin', 'Fulvic Acid Content': '85.4% Certified', 'Dosage': 'Pea-sized (300mg-500mg) in warm water or milk', 'Purity': '100% Solvent Free' },
    tags: ['shilajit', 'ayurveda', 'energy', 'herbal', 'immunity', 'minerals'],
    sku: 'HEA-SHI-001',
    deliveryEstimate: 'Dispatched within 6 hours',
    returnDays: 30,
    warranty: 'Certificate of Analysis Included'
  },
  {
    id: 'hea-2',
    name: 'ApexRecovery Pro Deep Tissue Percussion Massager',
    slug: 'apexrecovery-pro-deep-tissue-massager',
    category: 'health-wellness',
    categoryName: 'Health & Wellness',
    subcategory: 'Recovery & Massage',
    brand: 'ApexRecovery',
    price: 119.00,
    originalPrice: 169.00,
    discountPercent: 30,
    cashbackPercent: 12,
    rating: 4.86,
    reviewCount: 390,
    inStock: true,
    stockCount: 34,
    isFlashSale: true,
    flashSaleEndsInSeconds: 9800,
    flashClaimedPercent: 88,
    badge: '16mm Amplitude',
    images: [
      'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1574680096145-d05b474e2155?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'High-torque brushless motor delivering 60 lbs stall force and 16mm deep amplitude to relieve muscle soreness, trigger points, and accelerate post-workout recovery with whisper-quiet 35dB operation.',
    shortDesc: '60 lbs stall force, 6 titanium & silicone heads, 8-hour battery.',
    features: ['16mm Professional amplitude for real deep myofascial release', 'QuietGlide brushless motor (<38dB)', '6 Interchangeable attachments including heated head', 'OLED speed & battery indicator with 5 speeds (1400-3200 RPM)'],
    specs: { 'Stall Force': '60 lbs', 'Battery': '2600mAh (8 hours runtime)', 'Weight': '980g Ergonomic grip', 'Speed Modes': '5 Intelligent Speeds' },
    tags: ['massage gun', 'recovery', 'fitness', 'wellness', 'health'],
    sku: 'HEA-MAS-002',
    deliveryEstimate: 'Next Day Express Courier',
    returnDays: 30,
    warranty: '2 Year Motor Replacement Warranty'
  },

  // Home & Kitchen
  {
    id: 'hom-1',
    name: 'CastIron Artisan 6.5 Qt Enameled Dutch Oven',
    slug: 'castiron-artisan-enameled-dutch-oven-6-5qt',
    category: 'home-kitchen',
    categoryName: 'Home & Kitchen',
    subcategory: 'Cookware & Bakeware',
    brand: 'CastIron Artisan',
    price: 94.00,
    originalPrice: 135.00,
    discountPercent: 30,
    cashbackPercent: 10,
    rating: 4.93,
    reviewCount: 460,
    inStock: true,
    stockCount: 26,
    isBestSeller: true,
    isFeatured: true,
    badge: 'Heirloom Quality',
    images: [
      'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Cast from premium virgin iron with 3 layers of chip-resistant porcelain enamel. Self-basting lid spikes continuously recirculate juices for tender sourdough bread and slow-braised stews.',
    shortDesc: '6.5-Quart heavy cast iron with 3-coat vitreous enamel & gold knob.',
    features: ['Oven safe up to 500°F (260°C) with solid stainless brass knob', 'Compatible with Induction, Gas, Electric, and Ceramic tops', 'Self-basting interior condensation dots', 'Easy-clean smooth non-reactive enamel interior'],
    specs: { 'Capacity': '6.5 Quarts (6.1 Liters)', 'Weight': '6.2 kg', 'Material': 'Cast Iron + 3-Layer Porcelain Enamel', 'Diameter': '28 cm' },
    tags: ['dutch oven', 'cookware', 'kitchen', 'cast iron', 'baking', 'gourmet'],
    sku: 'HOM-DUT-001',
    variants: [{ name: 'Color', options: ['Emerald Pine', 'Terracotta Red', 'Midnight Navy', 'Matte Cream'] }],
    deliveryEstimate: 'Heavy Item Safe Courier',
    returnDays: 30,
    warranty: 'Lifetime Limited Warranty'
  },
  {
    id: 'hom-2',
    name: 'BaristaCraft Pro Dual-Boiler 15-Bar Espresso Machine',
    slug: 'baristacraft-pro-dual-boiler-espresso-machine',
    category: 'home-kitchen',
    categoryName: 'Home & Kitchen',
    subcategory: 'Coffee & Espresso',
    brand: 'BaristaCraft',
    price: 489.00,
    originalPrice: 620.00,
    discountPercent: 21,
    cashbackPercent: 12,
    rating: 4.88,
    reviewCount: 195,
    inStock: true,
    stockCount: 16,
    isNewArrival: true,
    badge: 'PID Temp Control',
    images: [
      'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Commercial Italian 15-bar pump with digital PID temperature control, dual thermo-block boilers for simultaneous brewing and microfoam steaming, and 58mm stainless portafilter.',
    shortDesc: 'Dual boiler system, 58mm commercial portafilter, pro steam wand.',
    features: ['Simultaneous espresso extraction and milk texturing', 'PID digital temperature control ±1°C accuracy', 'Commercial 58mm stainless steel portafilter included', '2.5L removable water tank with filtration cartridge'],
    specs: { 'Pressure': '15 Bar Italian ULKA Pump', 'Power': '1650W Fast Warmup', 'Boiler': 'Dual Stainless Thermo-block', 'Body': 'Brushed Stainless Steel 304' },
    tags: ['espresso machine', 'coffee', 'barista', 'kitchen appliance', 'latte art'],
    sku: 'HOM-ESP-002',
    deliveryEstimate: 'Free Express Insured Delivery',
    returnDays: 30,
    warranty: '2 Years Manufacturer Warranty'
  },

  // Mobile & Accessories
  {
    id: 'mob-1',
    name: 'VoltStream 100W GaN 4-Port Fast Desktop Charger',
    slug: 'voltstream-100w-gan-4-port-charger',
    category: 'mobile-accessories',
    categoryName: 'Mobile & Accessories',
    subcategory: 'GaN Fast Chargers',
    brand: 'VoltStream',
    price: 46.00,
    originalPrice: 65.00,
    discountPercent: 29,
    cashbackPercent: 15,
    rating: 4.9,
    reviewCount: 710,
    inStock: true,
    stockCount: 88,
    isBestSeller: true,
    isFlashSale: true,
    flashSaleEndsInSeconds: 7200,
    flashClaimedPercent: 94,
    badge: 'GaN III Tech',
    images: [
      'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1622445262464-84b1456045b6?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Powered by Navitas GaN III semiconductor chips, this compact wall adapter can charge a 16" laptop at full 100W speed or fast-charge 4 devices simultaneously with intelligent power allocation.',
    shortDesc: '100W GaN III (3x USB-C + 1x USB-A), foldable prongs, worldwide voltage.',
    features: ['Charges MacBook Pro 16" from 0 to 55% in 30 minutes', '3x USB-C PD 3.0 (PPS) + 1x USB-A QC 4.0 ports', '50% smaller than standard silicon chargers with cooler operation', 'Over-current, over-voltage, and thermal safety sensors'],
    specs: { 'Total Output': '100W Max', 'Input': '100-240V ~ 50/60Hz 2.4A', 'Dimensions': '65 x 65 x 32 mm', 'Weight': '210g' },
    tags: ['charger', 'gan', 'fast charge', 'usb-c', 'mobile accessories', 'power'],
    sku: 'MOB-CHA-001',
    deliveryEstimate: 'Next Day Dispatch',
    returnDays: 30,
    warranty: '18 Months Warranty'
  },
  {
    id: 'mob-2',
    name: 'MagSnap Armor Aerospace Carbon Fiber Magnetic Case',
    slug: 'magsnap-armor-carbon-fiber-case',
    category: 'mobile-accessories',
    categoryName: 'Mobile & Accessories',
    subcategory: 'Magnetic Cases & Covers',
    brand: 'MagSnap',
    price: 38.00,
    originalPrice: 52.00,
    discountPercent: 27,
    cashbackPercent: 10,
    rating: 4.82,
    reviewCount: 340,
    inStock: true,
    stockCount: 70,
    isNewArrival: true,
    badge: '1500D Aramid Fiber',
    images: [
      'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Constructed with genuine 1500D aerospace aramid carbon fibers 5x stronger than steel yet featherlight at 12g. Features ultra-strong N52 neodymium magnetic ring for flawless MagSafe lock.',
    shortDesc: '1500D Real Aramid Carbon Fiber, built-in N52 MagSafe array, 0.85mm thin.',
    features: ['Rare 1500D aramid ballistic fiber texture with 3D grip coating', 'N52 strong magnetic alignment with zero signal interference', 'Chamfered aluminum camera bezel protects lenses from drops', 'Scratchproof, bulletproof-grade material'],
    specs: { 'Thickness': '0.85 mm', 'Weight': '12.5 grams', 'Magnet': '38x N52 Neodymium Magnets', 'Compatibility': 'iPhone 15/16 Pro & Galaxy S24/S25 Ultra series' },
    tags: ['phone case', 'carbon fiber', 'magsafe', 'mobile cover', 'protection'],
    sku: 'MOB-CAS-002',
    variants: [
      { name: 'Model', options: ['iPhone 16 Pro Max', 'iPhone 16 Pro', 'iPhone 15 Pro Max', 'Galaxy S25 Ultra', 'Pixel 9 Pro'] },
      { name: 'Finish', options: ['Twill Black Weave', 'Crimson Red / Black', 'Forged Matte Carbon'] }
    ],
    deliveryEstimate: 'Delivered in 24 Hours',
    returnDays: 15,
    warranty: '1 Year Breakage Warranty'
  },
  {
    id: 'mob-3',
    name: 'SonicBuds Pro 2 Spatial Audio Low-Latency Earbuds',
    slug: 'sonicbuds-pro-2-spatial-audio-earbuds',
    category: 'mobile-accessories',
    categoryName: 'Mobile & Accessories',
    subcategory: 'True Wireless Earbuds',
    brand: 'SonicBuds',
    price: 68.00,
    originalPrice: 95.00,
    discountPercent: 28,
    cashbackPercent: 15,
    rating: 4.87,
    reviewCount: 430,
    inStock: true,
    stockCount: 45,
    isFlashSale: true,
    flashSaleEndsInSeconds: 15400,
    flashClaimedPercent: 72,
    badge: '35ms Ultra Latency',
    images: [
      'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Dual dynamic 11mm titanium diaphragm drivers with 42dB smart adaptive ANC, 35ms ultra-low gaming latency, 6-mic AI wind-noise cancellation, and IPX5 water resistance.',
    shortDesc: '42dB adaptive ANC, 35ms latency mode, 38h total battery with wireless charge.',
    features: ['Smart Adaptive Noise Cancellation adjusts to ambient noise levels', '35ms Low Latency Game & Movie Mode with zero lip-sync delay', '6-mic ENC ensures studio clear calls in windy streets', 'Supports Qi wireless charging case and USB-C fast charge'],
    specs: { 'Battery': '8h single bud / 38h with case', 'Waterproof': 'IPX5 Sweat & Rainproof', 'Bluetooth': 'v5.4 with AAC & LDAC', 'Weight': '4.2g per earbud' },
    tags: ['earbuds', 'wireless audio', 'tws', 'noise cancelling', 'gaming audio'],
    sku: 'MOB-EAR-003',
    variants: [{ name: 'Color', options: ['Matte Stealth Black', 'Frost White', 'Titanium Silver'] }],
    deliveryEstimate: 'Same day dispatch',
    returnDays: 30,
    warranty: '1 Year Replacement'
  }
];

export const DEALS_OFFERS: DealOffer[] = [
  {
    id: 'deal-1',
    code: 'AANOBAZAR20',
    title: 'Grand Superstore Welcome Voucher',
    subtitle: 'Flat 20% OFF on your entire first order across all 7 categories',
    discountText: '20% OFF',
    discountValue: 20,
    discountType: 'percentage',
    minSpend: 40,
    category: 'all',
    cashbackBonus: 5,
    expiresIn: 'Ends this Sunday at midnight',
    badge: 'Sitewide Popular',
    terms: 'Valid on all grocery, electronics, fashion, beauty, and mobile accessories. Maximum discount $50.'
  },
  {
    id: 'deal-2',
    code: 'FRESHGROCERY',
    title: 'Organic Pantry & Produce Savings',
    subtitle: 'Get $15 Instant Discount + Free Express 2-hour delivery on groceries',
    discountText: '$15 OFF',
    discountValue: 15,
    discountType: 'fixed',
    minSpend: 60,
    category: 'grocery',
    cashbackBonus: 8,
    expiresIn: 'Limited to first 500 shoppers today',
    badge: 'Express Grocery',
    terms: 'Applicable solely on items under the Grocery & Gourmet catalog.'
  },
  {
    id: 'deal-3',
    code: 'TECHCASHBACK',
    title: 'Electronics & Audio Mega Cashback',
    subtitle: 'Earn an additional 15% Instant Wallet Cashback on premium laptops, ANC audio & GaN gear',
    discountText: '15% Cashback',
    discountValue: 15,
    discountType: 'percentage',
    minSpend: 100,
    category: 'electronics',
    cashbackBonus: 15,
    expiresIn: 'Valid for next 48 hours',
    badge: 'Mega Cashback',
    terms: 'Cashback credited instantly to AANO Wallet on checkout completion.'
  },
  {
    id: 'deal-4',
    code: 'FASHIONLUXE',
    title: 'Designer Footwear & Cashmere Treat',
    subtitle: 'Save $25 on artisan leather footwear and Himalayan cashmere shawls',
    discountText: '$25 OFF',
    discountValue: 25,
    discountType: 'fixed',
    minSpend: 120,
    category: 'fashion',
    cashbackBonus: 10,
    expiresIn: 'Ends in 3 days',
    badge: 'Luxury Drop',
    terms: 'Applies on handcrafted leather and cashmere collections.'
  }
];

export const DEALER_TIERS: DealerTier[] = [
  {
    id: 'tier-silver',
    name: 'Authorized Silver Dealer',
    minMonthlyOrder: '$1,500 / mo',
    discountRate: '18% - 24% Wholesale Margin',
    creditPeriod: '7 Days Net Credit',
    dedicatedManager: false,
    freeLogistics: true,
    priorityDispatch: false,
    recommendedFor: 'Independent boutique shops, local grocery marts, and electronics retailers.'
  },
  {
    id: 'tier-gold',
    name: 'Executive Gold Dealer',
    minMonthlyOrder: '$5,000 / mo',
    discountRate: '28% - 35% Wholesale Margin',
    creditPeriod: '21 Days Net Credit',
    dedicatedManager: true,
    freeLogistics: true,
    priorityDispatch: true,
    recommendedFor: 'Multi-outlet retail chains, regional distributors, and e-commerce aggregators.'
  },
  {
    id: 'tier-platinum',
    name: 'Platinum Master Distributor',
    minMonthlyOrder: '$15,000+ / mo',
    discountRate: '38% - 48% Wholesale Margin + Rebates',
    creditPeriod: '45 Days Net Credit & Line of Credit',
    dedicatedManager: true,
    freeLogistics: true,
    priorityDispatch: true,
    recommendedFor: 'National distributors, institutional buyers, and bulk wholesale partners.'
  }
];

export const FAQ_ITEMS: FAQItem[] = [
  {
    id: 'faq-1',
    category: 'Ordering & Delivery',
    question: 'How do I track my order status in real time on AANO BAZAR?',
    answer: 'You can track your order anytime by clicking "Track Order" in the top bar or footer and entering your order reference number (e.g. AB-89241). You will see live dispatch updates from our nearest fulfillment hub, warehouse check-ins, and delivery courier details.'
  },
  {
    id: 'faq-2',
    category: 'Ordering & Delivery',
    question: 'What are the delivery timelines and express shipping options?',
    answer: 'Grocery items in designated metropolitan zones qualify for 2-hour express delivery. For electronics, fashion, and home goods, standard delivery is completed in 24 to 48 hours. Orders over $35 (or Rs. 2,000) receive 100% Free Superstore Shipping.'
  },
  {
    id: 'faq-3',
    category: 'Payments & Cashback',
    question: 'How does AANO BAZAR Wallet Cashback work?',
    answer: 'When you purchase products marked with the Cashback badge (up to 20%), the cashback amount is automatically calculated and credited to your AANO digital wallet upon order confirmation. You can use this balance immediately for your next purchase without any minimum spend restriction!'
  },
  {
    id: 'faq-4',
    category: 'Payments & Cashback',
    question: 'Which payment methods and digital wallets are accepted?',
    answer: 'We support all major Credit/Debit Cards (Visa, Mastercard, Amex), Digital Wallets (Apple Pay, Google Pay, eSewa, Khalti, bKash, Paytm), Net Banking, and Cash on Delivery (COD) across eligible pin codes.'
  },
  {
    id: 'faq-5',
    category: 'Returns & Refunds',
    question: 'What is the return window and refund process?',
    answer: 'We provide a 15 to 30-day hassle-free return window for electronics, fashion, beauty, and home goods, and a 7-day freshness guarantee on grocery items. Once initiated via our Return Policy tab, a courier picks up the product and your refund is processed to your original payment method or wallet within 24-48 hours.'
  },
  {
    id: 'faq-6',
    category: 'Product Quality & Warranty',
    question: 'Are all products 100% genuine with authentic brand warranties?',
    answer: 'Yes! All items listed on AANO BAZAR are verified directly through authorized brand manufacturers, certified distributors, or organic craft co-ops. Every electronic appliance comes with a manufacturer warranty card and certificate of authenticity.'
  },
  {
    id: 'faq-7',
    category: 'Sellers & Dealers',
    question: 'How do I start selling or register as a wholesale dealer on AANO BAZAR?',
    answer: 'Visit the "Sell on AANO BAZAR" or "Become a Dealer" tabs in the menu. Fill out our straightforward 3-minute onboarding form with your business details, tax ID (VAT/PAN/EIN), and product catalog. Our merchant verification team activates approved accounts within 24 hours.'
  },
  {
    id: 'faq-8',
    category: 'Sellers & Dealers',
    question: 'What wholesale margins and credit terms do dealers receive?',
    answer: 'Registered dealers get wholesale discount margins from 18% up to 48% depending on tier level (Silver, Gold, Platinum), along with flexible 7 to 45 days net credit terms, dedicated regional account managers, and zero-cost palletized logistics.'
  }
];

export const FAQS = FAQ_ITEMS;

